регистрация и авторизация + Хранение логинов/паролей
sashaaro/gophkeeper pull request #1
Opened 2024-10-26 21:24 UTC by sashaaro

GRPC протокол общения между клиентом и сервером
клиент, запускаемый через CLI
сервер
Реализация Ping метода на клиенте и сервере
Автозапуск линтера
Автозапуск тестов с вычислением покрытия
Создание релиза при создании релизного тега с версией в git репозитории
Сборка и выкладывание с релизом бинарников клиента
регистрация и авторизация
Хранение логинов/паролей

2024-10-28 11:37 UTC, s-shpak requested changes

2024-10-28 11:37 UTC, s-shpak commented on internal/server/keeper.go
> +//	func (s *KeeperServer) CreateCredentials(ctx context.Context, *gophkeeper.CreateCreadentialsReq) (*gophkeeper.Entity, error) {
deadcode

2024-10-28 11:37 UTC, s-shpak commented on pkg/gophkeeper/gophkeeper.proto
> +  repeated Tag tags = 2;
Поечму 2, а не 1 ?

2024-10-28 11:37 UTC, s-shpak commented on pkg/gophkeeper/gophkeeper.proto
> +  string number = 2;
Такой же вопрос

2024-10-28 11:37 UTC, s-shpak commented on pkg/gophkeeper/gophkeeper.proto
> +  rpc SendData(stream Chunk) returns(Empty);
Лучше возвращать не `Empty`, а `SendDataResponse`, который будет пустым

2024-10-28 14:15 UTC, sashaaro commented on internal/application/server_cli.go
> +	return &cli.App{
тут для сервера помимо его самого могут быть разные доп. команды. Тут допустим для удобства есть команда добавления пользователя.

2024-10-28 14:17 UTC, sashaaro commented on pkg/gophkeeper/gophkeeper.proto
> +  repeated Tag tags = 2;
Удалял видимо поле которые было до этого под = 1.

2024-10-28 14:17 UTC, sashaaro commented on internal/server/keeper.go
> +//	func (s *KeeperServer) CreateCredentials(ctx context.Context, *gophkeeper.CreateCreadentialsReq) (*gophkeeper.Entity, error) {
убрал

2024-10-28 14:17 UTC, sashaaro commented on internal/application/client_cli.go
> +						fmt.Printf("Fails. %v\n", err)
поправил

2024-10-28 14:17 UTC, sashaaro commented on internal/application/client_cli.go
> +		Usage:   "say a greeting",
поправил

2024-10-28 14:17 UTC, sashaaro commented on README.md
> +TLS_PUBLIC_KEY_PATH=/apps/yandex/keeper/data/server_cert.pem TLS_PRIVATE_KEY_PATH=/apps/yandex/keeper/data/server_key.pem go run ./cmd/server/
поправил

2024-10-28 14:18 UTC, sashaaro commented on .github/release/build.sh
понял! спс посмотрю как-нибудь

2024-10-28 14:18 UTC, sashaaro commented on pkg/gophkeeper/gophkeeper.proto
> +  string number = 2;
Удалял видимо поле которые было до этого под = 1.

2024-10-28 14:24 UTC, sashaaro commented on pkg/gophkeeper/gophkeeper.proto
> +  rpc SendData(stream Chunk) returns(Empty);
получается для каждого метода собственный пустой объект? CreateBinaryResponse, CreateTextResponse. Принцип понял.  поменял на пустой SendDataResponse

2024-10-31 19:28 UTC, s-shpak commented on pkg/gophkeeper/gophkeeper.proto
> +  rpc SendData(stream Chunk) returns(Empty);
Да, т.к. в будущем это позволит не ломать интерфейс, если эндпоинт начнет возвращать какие-то данные

2024-10-31 19:34 UTC, s-shpak requested changes
Правильно ли я понимаю, что пока основной функционал не реализован ?

Опиши, пожалуйста, подробнее как запустить и протестировать решение локально. Такой happy-path, допустим:
регистрация пользователя - логин - загрузка файла - получение файла от сервера

2024-11-10 18:51 UTC, sashaaro commented
> Правильно ли я понимаю, что пока основной функционал не реализован ?
> 
> Опиши, пожалуйста, подробнее как запустить и протестировать решение локально. Такой happy-path, допустим: регистрация пользователя - логин - загрузка файла - получение файла от сервера

доделал функционал. как запускать в редми
```
make certs
TLS_PUBLIC_KEY_PATH=./data/server_cert.pem TLS_PRIVATE_KEY_PATH=./data/server_key.pem go run ./cmd/server/
TLS_PRIVATE_KEY_PATH=./data/server_key.pem TLS_PUBLIC_KEY_PATH=./data/server_cert.pem go run ./cmd/client/ ui
```

2024-11-11 11:58 UTC, s-shpak approved these changes

2024-11-11 18:38 UTC, merged